
package bsr.server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AuthException", targetNamespace = "http://server.bsr/")
public class AuthException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AuthException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AuthException_Exception(String message, AuthException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AuthException_Exception(String message, AuthException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: bsr.server.AuthException
     */
    public AuthException getFaultInfo() {
        return faultInfo;
    }

}
