
package bsr.server.innerservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountService", targetNamespace = "http://innerServices.server.bsr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @return
     *     returns java.util.List<bsr.server.innerservices.Account>
     * @throws UserException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://innerServices.server.bsr/", className = "bsr.server.innerservices.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://innerServices.server.bsr/", className = "bsr.server.innerservices.GetAccountsResponse")
    @Action(input = "http://innerServices.server.bsr/AccountService/getAccountsRequest", output = "http://innerServices.server.bsr/AccountService/getAccountsResponse", fault = {
        @FaultAction(className = SessionException_Exception.class, value = "http://innerServices.server.bsr/AccountService/getAccounts/Fault/SessionException"),
        @FaultAction(className = UserException_Exception.class, value = "http://innerServices.server.bsr/AccountService/getAccounts/Fault/UserException")
    })
    public List<Account> getAccounts()
        throws SessionException_Exception, UserException_Exception
    ;

    /**
     * 
     * @param amount
     * @param title
     * @param targetAccountNumber
     * @return
     *     returns bsr.server.innerservices.Operation
     * @throws AccountServiceException_Exception
     * @throws NotValidException_Exception
     * @throws OperationException_Exception
     * @throws ServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "depositMoney", targetNamespace = "http://innerServices.server.bsr/", className = "bsr.server.innerservices.DepositMoney")
    @ResponseWrapper(localName = "depositMoneyResponse", targetNamespace = "http://innerServices.server.bsr/", className = "bsr.server.innerservices.DepositMoneyResponse")
    @Action(input = "http://innerServices.server.bsr/AccountService/depositMoneyRequest", output = "http://innerServices.server.bsr/AccountService/depositMoneyResponse", fault = {
        @FaultAction(className = NotValidException_Exception.class, value = "http://innerServices.server.bsr/AccountService/depositMoney/Fault/NotValidException"),
        @FaultAction(className = ServerException_Exception.class, value = "http://innerServices.server.bsr/AccountService/depositMoney/Fault/ServerException"),
        @FaultAction(className = AccountServiceException_Exception.class, value = "http://innerServices.server.bsr/AccountService/depositMoney/Fault/AccountServiceException"),
        @FaultAction(className = OperationException_Exception.class, value = "http://innerServices.server.bsr/AccountService/depositMoney/Fault/OperationException")
    })
    public Operation depositMoney(
        @WebParam(name = "title", targetNamespace = "")
        String title,
        @WebParam(name = "amount", targetNamespace = "")
        String amount,
        @WebParam(name = "targetAccountNumber", targetNamespace = "")
        String targetAccountNumber)
        throws AccountServiceException_Exception, NotValidException_Exception, OperationException_Exception, ServerException_Exception
    ;

}
