
package bsr.server.innerservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountService", targetNamespace = "http://innerServices.server.bsr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @return
     *     returns java.util.List<bsr.server.innerservices.Account>
     * @throws UserException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://innerServices.server.bsr/", className = "bsr.server.innerservices.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://innerServices.server.bsr/", className = "bsr.server.innerservices.GetAccountsResponse")
    @Action(input = "http://innerServices.server.bsr/AccountService/getAccountsRequest", output = "http://innerServices.server.bsr/AccountService/getAccountsResponse", fault = {
        @FaultAction(className = SessionException_Exception.class, value = "http://innerServices.server.bsr/AccountService/getAccounts/Fault/SessionException"),
        @FaultAction(className = UserException_Exception.class, value = "http://innerServices.server.bsr/AccountService/getAccounts/Fault/UserException")
    })
    public List<Account> getAccounts()
        throws SessionException_Exception, UserException_Exception
    ;

}
