
package bsr.server.innerservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AccountServiceException", targetNamespace = "http://innerServices.server.bsr/")
public class AccountServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccountServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AccountServiceException_Exception(String message, AccountServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AccountServiceException_Exception(String message, AccountServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: bsr.server.innerservices.AccountServiceException
     */
    public AccountServiceException getFaultInfo() {
        return faultInfo;
    }

}
